### ISSUE TITLE
Find a maintainer.

### ISSUE THREAD

**Issue by gilch** [hylang/vim-hy#17]
There's currently no-one responsible for maintaining vim-hy (PRs have been ignored for months). We're recommending that users edit Hy with Emacs since [hy-mode](https://github.com/hylang/hy-mode) is more up to date.

PRs will probably be ignored for the time being, but nothing is stopping anyone from making a fork.

**Comment by Foxboron** [comment]
I have no problems handing over maintainership to someone interested :) There shouldn't be a need for a fork.

**Comment by vilmibm** [comment]
hi!

while I am far from a vim scripting expert, I'd like to see a base-level, up to date plugin for Hy for vim. I use vim to develop [tildemush](https://github.com/vilmibm/tildemush), a MUSH which uses Hy as a scripting layer.

I'm more than happy to take over maintainership and help shepherd through some of the last year's PRs.

I've used Hy over the years since its initial announcement and am a big fan.

**Comment by Foxboron** [comment]
@vilmibm Hi! I have added you as a collaborator :) There is a viminions teams on the org but I don't have the ability to add people. Possibly @Kodiologist or @kirbyfan64 could probably send out an invite.

**Comment by Kodiologist** [comment]
I've sent an invitation. Welcome aboard!

**Comment by vilmibm** [comment]
awesome, thanks y'all!
